### ISSUE TITLE
Generate new dir under 'myoutdir' 

### ISSUE THREAD

**Issue by ehsandeep** [anshumanbh/brutesubs#2]
while scanning each time results goes under same dir '**myoutdir**' for all targets which create conflicts.
it will be good if output will generate like '**myoutdir/target.tld/output-result**', so we dont need to delete each time the '**myoutdir**' while new scan.

**Comment by anshumanbh** [comment]
Thanks for the feedback. Ill get this done asap

**Comment by anshumanbh** [comment]
@s4ndeeps Done. Specify whatever directory you want the results to be saved inside the `myoutdir` directory by specifying the environment variable `DIRNAME` and you should see the outputs being saved to that directory.
