### ISSUE TITLE
cewl won't work for targets which is accessible via www. 

### ISSUE THREAD

**Issue by ehsandeep** [anshumanbh/brutesubs#4]
in **.env** file target expect value like : target.com, but if target.com is acciessible in www.target.com manner then cewl wont wont create list for target.com and whole automation will get stuck at start only.

and if we add www.target.com in **.env** file then cewl will genarre the list whole subdomain process get failed as tool will find new subdomains in this manner **newsub.www.target.com** which is not valid.

![image](https://cloud.githubusercontent.com/assets/8293321/19172081/a4de1272-8c3d-11e6-8a76-2c88ab7aed43.png)

**Comment by anshumanbh** [comment]
@s4ndeeps Yes, good point. I think I am going to remove cewl all together for this and many other reasons. It was creating more problems than creating words that might be used to bruteforce. Thanks!

**Comment by ehsandeep** [comment]
yeah i was about to ask that only, cewl is created much of unwanted list, which is increasing the time only to brute with useless keyword, so removing that will be better idea.

**Comment by anshumanbh** [comment]
@s4ndeeps removed cewl. please try again!
